language: node_js
node_js:
  - 16
# echo "c33d975f-8f3d-49eb-b18f-7c82dde1f6de" | sudo docker login -u "abdelrahmansherif" --password-stdin
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend abdelrahmansherif/udacity-udagram-frontend:latest

# Tasks to perform after the process is successful. Formatting the Docker 
# username and password as below enables you to programmatically log in 
# without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abdelrahmansherif/udacity-udagram-frontend